spring:
  config:
    activate:
      on-profile: dev

  datasource:
    url: ${DATASOURCE_URL:jdbc:mysql://chick.ci1frsfm7h8y.ap-northeast-2.rds.amazonaws.com:3306/chick2?useSSL=false&serverTimezone=UTC&useUnicode=true&characterEncoding=UTF-8&allowPublicKeyRetrieval=true}
    username: ${DATASOURCE_USERNAME:root}
    password: ${DATASOURCE_PASSWORD:password1}

  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    open-in-view: false
    properties:
      default_batch_fetch_size: 100
      hibernate:
        format_sql: true
